apiVersion: v2
name: wearsphere # Name of HELM Chart
metadata:
  namespace: wearsphere
description: A Helm chart for Kubernetes

type: application

version: 0.1.0

appVersion: "1.0.0"

dependencies:
  - name: admin
    version: 0.1.0
  - name: frontend
    version: 0.1.0
  - name: backend
    version: 0.1.0
  - name: mongodb
    version: 13.6.4
    repository: https://charts.bitnami.com/bitnami
