replicaCount: 3

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

ingress:
  ingressClassName: alb
  host: wearsphere.cctlds.online
  frontendPort: 5173
  backendPort: 4000
  adminPort: 5174
