apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-deployment
  namespace: wearsphere
  labels:
    app: admin
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
      - name: admin
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.service.port }}
        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.service.port }}
          initialDelaySeconds: 15
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.service.port }}
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 3
        env:
        - name: VITE_BACKEND_URL
          value: "http://backend-service:4000"
        - name: ULIMIT_NOFILE
          value: "65536"
