apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: wearsphere
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: {{ .Values.backendPort }}
      targetPort: {{ .Values.backendTargetPort }}

